### ISSUE TITLE
chat avatars

### ISSUE THREAD

**Issue by bitkarrot** [HiveTalk/hivetalksfu#11]
- In video below, the nostr profile opens to an external window. the link should be a more visible button, such as dropdown
- Also see chat avatars in chat are not matching the nostr logged in avatar. Random name avatars are OK. 

https://github.com/HiveTalk/hivetalksfu/assets/73979971/58f6b487-76c2-44da-9261-651d4fc5cc8b

**Comment by bitkarrot** [comment]
@Yeghro

**Comment by bitkarrot** [comment]
@Yeghro can you please comment on this thread, somehow i can't assign it to you unless you comment here it seems :p

**Comment by Yeghro** [comment]
> @Yeghro can you please comment on this thread, somehow i can't assign it to you unless you comment here it seems :p

Sure.

**Comment by EthnTuttle** [comment]
https://robohash.org/

**Comment by EthnTuttle** [comment]
https://robohash.org/
For random names?

**Comment by bitkarrot** [comment]
> https://robohash.org/ For random names?

Is it available as an open source library? would prefer not to link to an external site.

**Comment by EthnTuttle** [comment]
Nope! Good point.

**Comment by bitkarrot** [comment]
ref https://github.com/HiveTalk/hivetalksfu/pull/85
