### ISSUE TITLE
fix layout on front page for rooms

### ISSUE THREAD

**Issue by bitkarrot** [HiveTalk/hivetalksfu#14]
layout not centered, for rooms - see image below

<img width="1256" alt="Screenshot 2024-06-27 at 7 34 59 PM" src="https://github.com/HiveTalk/hivetalksfu/assets/73979971/bf32cff9-96aa-4a35-afd6-7480ce058538">

**Comment by Yeghro** [comment]
would this be adequate ?
![image](https://github.com/user-attachments/assets/dbc820d2-5ea7-4234-aa0b-53172ed72641)

**Comment by bitkarrot** [comment]
@Yeghro That's pretty good on the box layout, the last RoomID, if it can wrap and stay inside of the box, would be great.

Not sure max limit for Room ID#s but there probably is one somewhere. :D

How does it look on mobile?  does it scale down to 1 column?

**Comment by Yeghro** [comment]
And yes on mobile it lists the button in a single row.

![image](https://github.com/user-attachments/assets/e9ccbdd5-630d-435e-bca9-f37ae9d498cb)

**Comment by bitkarrot** [comment]
Looks good. Am looking forward to reviewing it!

**Comment by bitkarrot** [comment]
@Yeghro is there a PR for this or did it miss it somehow?

**Comment by Yeghro** [comment]
Yes it was included in one of the PRs.

![image](https://github.com/user-attachments/assets/d41bd2ec-434c-41fc-ac65-1de949dda0d4)

**Comment by bitkarrot** [comment]
Ah Thanks!  Lets close this issue then. Thank you!
