### ISSUE TITLE
unable to login using nsec.app

### ISSUE THREAD

**Issue by 1440000bytes** [HiveTalk/hivetalksfu#15]
![image](https://github.com/HiveTalk/hivetalksfu/assets/147166694/9f1e63f8-c49c-411f-84e3-81330b90810e)

**Comment by bitkarrot** [comment]
will forward this to nostr-login, as this logic appears to be on their side

**Comment by nostrband** [comment]
Looks like the "name" field was left empty when you clicked "Sign up". We should fix validation on nostr-login, but outside of that I don't think anything is wrong - just tested it, signup seems to work fine.

**Comment by bitkarrot** [comment]
@1440000bytes  if you can kindly please try again, would be much appreicated. thanks.
