### ISSUE TITLE
Option to hide room from 'active rooms'

### ISSUE THREAD

**Issue by 1440000bytes** [HiveTalk/hivetalksfu#18]
There should be an option to hide the room from active rooms because not everyone wants to make their video calls public

![image](https://github.com/HiveTalk/hivetalksfu/assets/147166694/4df42c49-1334-4813-a8f8-d644134056e1)

**Comment by bitkarrot** [comment]
good idea. maybe we add this to the private server and have one that is more social and public oriented

**Comment by bitkarrot** [comment]
Easier solution: 

If Mod Locks a room with a password, it doesn't show up on the API and in turn the front page (which just polls API for rooms). Should be fairly easy to make that modification in the API settings. 

Once the room is unlocked or the mod leaves the room will show up again in the API.

**Comment by bitkarrot** [comment]
Closing as completed 

071e5818a5557f53cdd01173949c8afb17edc2b6
