### ISSUE TITLE
Audio bug issue

### ISSUE THREAD

**Issue by ttiiggss** [HiveTalk/hivetalksfu#23]
Encountering a problem that's cropped up a few times now, seems like 90% or all laptops have a audio bug issue where the participant can hear but we can't hear a thing they're saying. 

Not sure on browser model but I'm guessing the latest, 

- Chrome, Firefox, Librewolf, Brave. 

- Tried Ubuntu and Windows. 

- Connected via hefty/fast line at some business and then also tether to mobile, no VPN

- Don't think the people are using a headset in probably all circumstances... onboard webcam mic and maybe 3.5mm audio out only.

- Connection / reliability of sound working seems a little random.

**Comment by bitkarrot** [comment]
Are they enabling Mic when they join the room? There are two audio dialog pop ups before they enter the room if one of them is not accepted then they can't be heard (its the 3rd dialog pop up)

**Comment by Nomishka** [comment]
I also have a sound issue in hivetalks meetings. The issus is others could hear me well. Also I could hear them but with a very low sound. What would be the issue? My specifications are below.

* Chrome brower.

* Ubuntu 24.04LTS OS.

* Connecting with Alby extension to the room.

When I connect my earbuds it is lot better. Mostly the issue happens when I don't use any headphones or earbuds.

**Comment by jeremyd** [comment]
@Nomishka i run linux also, my suggestion would be to check your audio settings and see if you just have your audio turned down .. hivetalk does not do automatic volume levels and they may need adjusting.  You can also check in the hivetalk settings to make sure you've selected the audio device that you expect (when you have multiple audio devices perhaps you're using a different one than you think).

**Comment by bitkarrot** [comment]
@ttiiggss is this still an on going issue? If yes please post details about operating system and any screenshots or short videos of how people are using. 

Otherwise we will close this issue for now

**Comment by bitkarrot** [comment]
@Nomishka @ttiiggss  you can also try to adjust the Advance options for audio here in this section and see if it helps with the audio. Might need to turn the "Auto gain control" function on. 

Closing issue for now. 

<img width="687" alt="Screenshot 2024-08-11 at 11 38 05 PM" src="https://github.com/user-attachments/assets/a56a2682-ecd4-4464-a80a-b73cd67d5d9f">

**Comment by Nomishka** [comment]
@bitkarrot Thanks for your recommendation and I will try it.
