### ISSUE TITLE
text chat is not very usable on mobile.

### ISSUE THREAD

**Issue by Yeghro** [HiveTalk/hivetalksfu#27]
When the text chat button is clicked in a chat room it opens up on the right sidebar but is not usable.  It's such a small area that you can hardly read the text and I can't seem to find the input area to try an type anything.

**Comment by bitkarrot** [comment]
So, originally text area is not pinned, but it was requested to be default pinned by @MORRA-RM 

To best address this, the chat should be full screen on mobile, there should be a peer_info that indicates if the user is on mobile or desktop. this way the default setting to full screen for mobile and for desktop it should be pinned. 

@Yeghro its a fairly simple issue, to fix.  would you like to work on it? LMK and we can assign it to you

**Comment by Yeghro** [comment]
Sure I can give it a go.

**Comment by bitkarrot** [comment]
Closed as per https://github.com/HiveTalk/hivetalksfu/pull/30

Thank you @Yeghro !
