### ISSUE TITLE
When saving video crashes in Firefox

### ISSUE THREAD

**Issue by storytellerjr** [HiveTalk/hivetalksfu#31]
Using firefox 129.0.1 (64 bits) on a Macbook Pro, Apple M1 Pro when saving a recording Hivetalk crashes.

I'm not able to start a recording and stop it and do multiple recordings either.

I have tested it multiple times, but it continues happening.

**Comment by bitkarrot** [comment]
@storytellerjr do you have any pop up blockers? 

Just tested on a M1 Macbook pro (Sonoma 14.5), Firefox 129.0.1 and it saving just fine. see screenshots below for my settings: 


<img width="672" alt="Screenshot 2024-08-17 at 5 05 11 PM" src="https://github.com/user-attachments/assets/22e41846-b89d-40f5-b884-312a3d8a7eb9">

<img width="523" alt="Screenshot 2024-08-17 at 5 04 45 PM" src="https://github.com/user-attachments/assets/d7ab8fb8-84d9-4789-843e-d1ad6f6d96cf">

<img width="467" alt="Screenshot 2024-08-17 at 5 04 26 PM" src="https://github.com/user-attachments/assets/e47e374e-3473-4b03-a4f0-b70f0d117b06">

**Comment by storytellerjr** [comment]
@bitkarrot I will check the pop up blockers. That might be true. If that is the case it us on my end.
Then we need to just mention to users that they need to allow pop ups for Hivetalk to be able to record. And specify what types of pop ups to allow. Thanks

**Comment by bitkarrot** [comment]
Pull requests to the FAQ page are welcome on the main repository

**Comment by bitkarrot** [comment]
Issue resolved, it was a pop up blocker.
