### ISSUE TITLE
UX improvement on User Square + Avatar

### ISSUE THREAD

**Issue by bitkarrot** [HiveTalk/hivetalksfu#32]
- Instead of having all the buttons on the avatar show up, hide them and only show up on mouse over with a sliding screen. 
- Move the lightning zap button into the same area, where it is only visible on mouse over or tap to show (on mobile)
- Rationale: this would enable a cleaner look on mobile where the screen is small. 

See example where the CSS would need to be modified. 

## Current UX

- See this code section for where these audio/msg/send etc  buttons start :  https://github.com/HiveTalk/hivetalksfu/blob/37dd491c7dd7262dc0307fa6180b0adea44aa9ea/public/js/RoomClient.js#L2477 

<img width="200" alt="Screenshot 2024-08-16 at 1 42 14 PM" src="https://github.com/user-attachments/assets/91619a93-9074-4f21-af8e-d9a89fb0ecb8">

- nostr Icon is hidden at the moment. Lightning icon shown. see https://github.com/HiveTalk/hivetalksfu/blob/37dd491c7dd7262dc0307fa6180b0adea44aa9ea/public/js/RoomClient.js#L2547) 

<img width="200" alt="Screenshot 2024-08-19 at 1 32 14 PM" src="https://github.com/user-attachments/assets/82e77bfc-4701-488a-a06e-f7059297c855">

### - HIDE ALL FRONT FACING BUTTONS (including lightning zap and Nostr Icon - which is currrently not visible) to Overlay Slide, unless requested ON DEMAND:  as illustrated in this example: 

https://github.com/user-attachments/assets/bda142dd-e8c3-468d-a8b2-b0e38acaa080

https://www.youtube.com/watch?v=yfg9ChTmuKM

This would prevent visual overload on mobile and a much cleaner look if the buttons on avatar squares are not shown unless on demand. 

Prefer this view shown at all times, with no buttons on avatar, 
unless user clicks or taps on a specific avatar square. The side navigation bar can be shown, that is ok. 

![photo_2024-08-19 13 40 53](https://github.com/user-attachments/assets/5384b601-f774-4a33-a5e7-149be28cd1e0)

We want the overlays slide to show the buttons on demand, instead of this current view which is too busy and overwhelming : 
![photo_2024-08-19 13 40 43](https://github.com/user-attachments/assets/ab2ea534-7919-4d66-a28c-09a5ce4654e3)

**Comment by bitkarrot** [comment]
- Take note for video on, there are 6 function buttons, + 2 for nostr+ln, 
for a total of 8 buttons that need to fit on the square for a very small screen.

**Comment by bitkarrot** [comment]
Full screen example from clubhouse, we will need it for the nostr profile information on a small screen. 

https://video.nostr.build/76c37d28aacfe0cf713b3431bc51d2f5d83fce265e720f0cc98c9b034ccdd550.mp4

**Comment by Yeghro** [comment]
@bitkarrot How does this look to you?


https://github.com/user-attachments/assets/a6db51a1-fae8-4b49-b2fe-33c902c830d3

**Comment by bitkarrot** [comment]
@Yeghro  its a good start for the mobile; might be good to show which user the current pull up is referring to, at a minimum username. 

I can do a mockup for the layout if that would be helpful, a grid might be better than than just vertically listing the icons. the clubhouse layout is too busy looking but there are spacing elements we can certainly borrow from there. 

lmk at anytime if you have questions.

**Comment by bitkarrot** [comment]
@Yeghro  some mockups, hope this helps. let me know if anything unclear

![3](https://github.com/user-attachments/assets/50171336-5f23-42b2-aff7-3997de650fcf)
![4](https://github.com/user-attachments/assets/2ffc1f7f-245a-4c46-8b3f-d82d59147235)

**Comment by Yeghro** [comment]
I've made some progress, let me know what you think:

https://github.com/user-attachments/assets/5c891b72-7e9a-40fc-87e7-c4d61a598617

still working on getting the Nostr logo inside the header container with the user name but it likes being at the bottom corner for some reason.  Probably some css I'm overlooking.
