### ISSUE TITLE
RTMP URL

### ISSUE THREAD

**Issue by marathon-gary** [HiveTalk/hivetalksfu#37]
Do meeting have an RTMP URL that can be leveraged for streaming via OBS or similar?

**Comment by marathon-gary** [comment]
https://docs.mirotalk.com/mirotalk-sfu/rtmp/

**Comment by bitkarrot** [comment]
@marathon-gary there is an RTMP server but its coming in next update. no ETA right now.

**Comment by EthnTuttle** [comment]
@bitkarrot 
Would you accept a PR to reintroducing the RTMP piece?

**Comment by bitkarrot** [comment]
All of the changes upstream from mirotalksfu need to pulled in from approximately May 2024
until now.  Ideally the RTMP should be pulled in and merged along with all other changes in 1 PR. 

If you are up for the challenge, please feel free to do so!!  There is also a current bug in the fonts merge, so latest deploy is 2 commits up the tree. i haven't had time; the next two weeks are kind killer for me in other areas of work.

**Comment by bitkarrot** [comment]
> @bitkarrot Would you accept a PR to reintroducing the RTMP piece?

Yes, I have assigned the PR to you Thanks @EthnTuttle

**Comment by EthnTuttle** [comment]
I'm going to try a rebase onto their latest stable release branch.
Open to alternative ideas as I'm unfamiliar with the codebase.

**Comment by bitkarrot** [comment]
> I'm going to try a rebase onto their latest stable release branch. Open to alternative ideas as I'm unfamiliar with the codebase.

That should work, it will likely be just our renaming that are conflicts, and whatever we added or adjusted. We've tried to keep our fork content as separate as possible. 

If it doesn't work out let me know, you can just do the rtmp and I'll cover the rest. 
The other outstanding PRs from Yeghro shouldn't conflict as its just a UI/UX display update

**Comment by EthnTuttle** [comment]
oh boy, I rebased and now it won't even let me PR because of the grossly divergent git history. It also seems to have added me as a committer on all the hivetalksfu commits that were rebased. 
This probably makes this messier than needed, let me try a different strategy.

**Comment by bitkarrot** [comment]
> oh boy, I rebased and now it won't even let me PR because of the grossly divergent git history. It also seems to have added me as a committer on all the hivetalksfu commits that were rebased. This probably makes this messier than needed, let me try a different strategy.
> 
> Edit: I see why, HiveTalk started with an init commit that squashed everything prior. I'll see what I can do.

oooh sorry!  that was probably my bad. If there is anything I can do to help adjust let me know 🥹

**Comment by EthnTuttle** [comment]
no worries. I just think a different strategy will be needed to update from mirotalk. I'll take another pass at it soon.

**Comment by bitkarrot** [comment]
OK i appreciate it. 😄

**Comment by bitkarrot** [comment]
@EthnTuttle  - not sure if you have made any progress with the rebase, we ( me and @jeremyd ) are looking at just forking miro upstream to a new repo and then merging in the changes from this one to make it more easily maintainable moving forward instead of this being its own independent repo; primarly due to the frequent updates from upstream we figure this would be the more efficient way forward. 

Do let me know if you have any thoughts. we'll likely be digging in this coming weekend.  Also find us on [simplex]( https://nostree.me/bitkarrot@nostr.com) if you're on there.

**Comment by EthnTuttle** [comment]
I have not had a chance to give it another pass, but my branch might be close to what you're looking for: https://github.com/EthnTuttle/hivetalksfu
Maybe I can save you some time on the endeavor.
The shared commit history will definitely help with merging in upstream changes.

**Comment by bitkarrot** [comment]
I think we got it. @jeremyd  did a rebase. Thanks @EthnTuttle

**Comment by EthnTuttle** [comment]
Awesome! Sorry I couldn't land it for you. Is there a timeline for deployment now that it's merged? Also, is there an npub for @jeremyd , I'd like to zap him for his efforts and direct some other interested parties to do so as well.

**Comment by bitkarrot** [comment]
@EthnTuttle  no ETA the moment, I am still working out details along with all of the other open issues. Once it goes live, will be sure to announce on my nostr account


https://nostr.band/npub10npj3gydmv40m70ehemmal6vsdyfl7tewgvz043g54p0x23y0s8qzztl5h
