### ISSUE TITLE
Chromium Crash

### ISSUE THREAD

**Issue by ArthurAmendt** [HiveTalk/hivetalksfu#38]
When I try to send a file to a user in chat -- if I add a space after the file it crashes the browser.
![Screenshot from 2024-08-25 19-48-19](https://github.com/user-attachments/assets/deb2adc0-1822-4304-9f14-0ef6fc3f7f9a)

**Comment by bitkarrot** [comment]
@ArthurAmendt It appears you filed the issue in the wrong repository so I have moved it to the correct one. Thanks for reporting!

**Comment by bitkarrot** [comment]
if this issue still persists, we should file it upstream, not here @MORRA-RM

**Comment by bitkarrot** [comment]
closing as fixed upstream
