### ISSUE TITLE
Mute all participants on Join 

### ISSUE THREAD

**Issue by bitkarrot** [HiveTalk/hivetalksfu#41]
- default settings to mute all users on entry and can't unmute themselves unless by moderator

![image](https://github.com/user-attachments/assets/8a070a9b-21a1-4040-b93a-f0d789d4ac7c)

**Comment by bitkarrot** [comment]
@MORRA-RM  please check staging for latest updates

**Comment by MORRA-RM** [comment]
In regards to muting. The room now starts with all the permissions open. 
![pic](https://github.com/user-attachments/assets/db5c2339-a893-4328-9655-b5e5a6e74c06)
The only issue I see is if you enable 'Everyone can't unmute themselves' by itself 
![pic](https://github.com/user-attachments/assets/c8fd6f35-8b72-4baa-a265-31f050ef3bf3)
If the participant mutes themselves they cant unmute again. If the Moderator allows users to come in unmuted the participant should be able to unmute themselves. Should this function be unavailable unless the 'Everyone starts muted' function is enabled??

**Comment by bitkarrot** [comment]
@MORRA-RM  Please test the latest on staging. It appears the upstream has made significant changes, best if you can get a few people in the room with you to test it out as its not the same setup as before for many features.

**Comment by MORRA-RM** [comment]
Retested from earlier. Same results. Produced with multiple logins on different browsers

**Comment by bitkarrot** [comment]
Well, we're going to have to just go with what we have here, if it continues to be an issue, better to file an issue upstream with mirotalk and see what their recommendation is. 

Closing issue.
