### ISSUE TITLE
Add ability to display images in chat

### ISSUE THREAD

**Issue by bitkarrot** [HiveTalk/hivetalksfu#49]
- add ability to display images that end in .png, .jpeg. .webp .gif in the chatroom

**Comment by Gudnessuche** [comment]
as well as GIFs

**Comment by bitkarrot** [comment]
@Gudnessuche  It appears this is already possible, but not sure if gifs weren't. 

@MORRA-RM was posting images the other day in hivetalk chat, perhaps he can clarify what kinds he was posting and how.

**Comment by MORRA-RM** [comment]
@Gudnessuche Yes .gif works. Like if you wanted to add a link in directly from GIPHY. But I pull alot of media from different places so the cheap easy fast 'cheat code' for me is just putting everything through [Nostr Build](https://nostr.build/) This is how I was posting screen shots in the chat

**Comment by bitkarrot** [comment]
closing as it sounds like issue is resolved.
