### ISSUE TITLE
Transcript display bug

### ISSUE THREAD

**Issue by bitkarrot** [HiveTalk/hivetalksfu#54]
We found two issues while testing inside the staging server with @jeremyd 

Second issue/more of a bug: Transcript feature has a bug where if you click the eye for it to disable transcript it’ll still show up from the bottom notification area and overlay on top of whatever you’re doing in that area, specially annoying when you’re typing and using the keyboard inside of chat, one of the most annoying parts about it is it can take that whole section over and not let you finish typing or sending the message. Build: IPhone 15 Pro Max IOS 18.1 ![image](https://github.com/user-attachments/assets/66d0f5fe-3e11-422b-9b22-3020a3d3ce9e)

_Originally posted by @ser-sleepy in https://github.com/HiveTalk/hivetalksfu/issues/34#issuecomment-2347073150_

**Comment by bitkarrot** [comment]
@AnUnknownB  please test on android, and iphone. thanks.

**Comment by AnUnknownB** [comment]
Tested issue on iPhone 11 (16.6.1) and Pixel 7 (Android 14- hive says 10), can confirm obstruction of keyboard while transcriptions are hidden but a chat member is still talking. No known temp fixes currently.
Also even if all of the participants mics are off, transcriptions still happen if the feature is not toggled off.

**Comment by bitkarrot** [comment]
We will disable the transcript feature for now. Too many other things to triage atm
