### ISSUE TITLE
Mobile Safari autoplay videos (staging)

### ISSUE THREAD

**Issue by bitkarrot** [HiveTalk/hivetalksfu#55]
We found two issues while testing inside the staging server with @jeremyd 

First issue: Mobile safari doesn’t auto play videos when shared to me but it does auto play when I share it (solution could be to add a button for the admin to toggle on/off auto play for media/ button should be inside media settings) 

_Originally posted by @ser-sleepy in https://github.com/HiveTalk/hivetalksfu/issues/34#issuecomment-2347073150_

**Comment by bitkarrot** [comment]
Assigning to @MORRA-RM  for testing on staging. there are many changes which are more fine grained, specific to browser instead of general

**Comment by MORRA-RM** [comment]
Tested and same results as original first issue with iPhone 6s running iOS 15.8.3 on Safari using DuckDuckGo as the search engine

**Comment by bitkarrot** [comment]
if this issue still persists, please file it as a bug upstream (mirotalk), this would be a better option than for us to do potentially redundant work. @MORRA-RM
