### ISSUE TITLE
Android speaker not working in certain browsers

### ISSUE THREAD

**Issue by MORRA-RM** [HiveTalk/hivetalksfu#56]
While trying to connect with MrHodl he couldnt hear me. He was using a samsung phone. We first tried DuckDuckGo then moved to Firefox with no success. Only when he used Chrome was he able to hear. This was all done in the same room that I opened and never left or changed any settings. I was on my desktop OS. I dont have any more information about his phone but i can get it if you need it. 
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bitkarrot** [comment]
assigning to @MORRA-RM  please test on staging with latest updates. thanks.

**Comment by bitkarrot** [comment]
ref https://github.com/HiveTalk/hivetalksfu/pull/62

**Comment by bitkarrot** [comment]
@AnUnknownB tested this and its working
