### ISSUE TITLE
FF on OSX required track missing on video enable 

### ISSUE THREAD

**Issue by bitkarrot** [HiveTalk/hivetalksfu#65]
**Describe the bug**
firefox video and screenshare cannot be enabled.

**To Reproduce**
Login to hivetalk and enable video

**Expected behavior**
Should enable video but produces this error instead on firefox browser

**Screenshots**
<img width="469" alt="Screenshot 2024-09-15 at 10 45 12 PM" src="https://github.com/user-attachments/assets/6f08a874-4e39-4625-8196-34dbbbb6e5a5">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Firefox
 - Version 130.0

**Comment by Yeghro** [comment]
is this specific to macos?  I just tried firebox on windows was able to share video.

**Comment by bitkarrot** [comment]
Might be. Its been an issue on OSX Sonoma 14.5 since about last week when i updated. 

What version of FF are  you running on Windows? @Yeghro

**Comment by bitkarrot** [comment]
ok. yep it was my browser issue,  all good now
