### ISSUE TITLE
Display Settings - issue

### ISSUE THREAD

**Issue by ser-sleepy** [HiveTalk/hivetalksfu#71]
https://v.nostr.build/HPpKARB7OHFWewJT.mp4

**Comment by AnUnknownB** [comment]
An alternate way to resolve this issue, zoom out in your browser and the settings panel will come into scale so you're able to click the close button.
Another option is to click the full screen option and drag the settings panel down a bit before exiting full screen.
(It seems like you're using chrome; this works with every browser)
