### ISSUE TITLE
{Chat Room} Links to open into new tab/window

### ISSUE THREAD

**Issue by AnUnknownB** [HiveTalk/hivetalksfu#73]
**Is your feature request related to a problem? Please describe:**
It would be a lot easier to have links sent in the chat open into a new tab/window to avoid leaving the room. 

**Describe the solution you'd like:**
It would be great if the hyperlinks that are posted into the chat open to a new browser tab.

**Describe alternatives you've considered:**
Temporarily can be avoided by right clicking to the menu and selecting opening the link to a new tab. Or copying the link and pasting it into your browser.
[![Chat-Link-Issue.png](https://i.postimg.cc/3JSFyTMz/Chat-Link-Issue.png)](https://postimg.cc/Cz8qt9x4)

**Additional context:**
The links sent in the chat will redirect you to the page and you will end up leaving the room.

**Comment by bitkarrot** [comment]
Appears to be fixed already, links have _blank in them. as of commit fdcd83eacb97aad1e2989cf80d4ce8a9dcab01b1


https://github.com/user-attachments/assets/9bc952f7-425e-4a7a-a361-d1f5dc01366a

**Comment by bitkarrot** [comment]
See upstream issue filed at mirotalk . Its better for use to let upstream deal with the brave issue on links than use trying to fix it for now, so as not to duplicate work. 

https://github.com/miroslavpejic85/mirotalksfu/issues/168
