### ISSUE TITLE
Homepage text (display improvement)

### ISSUE THREAD

**Issue by AnUnknownB** [HiveTalk/hivetalksfu#78]
**Is your feature request related to a problem? Please describe.**
It was brought up that the homepage is difficult to read. 

**Describe the solution you'd like**
It would be great to have a transparent background to help highlight the text on screen. 

**Describe alternatives you've considered**
Alternatives could be as simple as changing the color, the text size or even font.
This link was provided by Jurjen to help:
https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html

**Additional context**
Making the front page accessible to for everyone to see is important so we can show everyone how amazing HiveTalk is.

**Comment by bitkarrot** [comment]
ref https://github.com/HiveTalk/hivetalksfu/issues/78
