### ISSUE TITLE
DMs show up in main chat

### ISSUE THREAD

**Issue by bitkarrot** [HiveTalk/hivetalksfu#87]
**Describe the bug**
when we had 8+ users on the room, some of the DMs showed up in the main chat instead of as a DM

**Further investigation**

From @Yeghro 
After some more testing, it turns out I didn’t really fix the private message issue, but I did find that the issue stems from new users entering the chat caused the issue to happen. If you have a private chat window open and somebody enters the chat it glitches out and makes your next private message public.  This can be avoided by reselecting the pier you want to private message and then sending  the message. 

I just tested mirotalk sfu and they also have this bug. 

**Corrective Action**
file bug upstream to mirotalk and let them resolve bug and then we will merge into our main when its released.

**Comment by Yeghro** [comment]
more testing revealed that it doesn't take 8 or more this can happen even if 2 people are in a room private chatting and and new peer joins while they are messaging it will make the next DM public.

**Comment by bitkarrot** [comment]
Thanks @Yeghro

**Comment by bitkarrot** [comment]
fixed and closed upstream. will merge into our main soon
